version: '3.1'

services:
  couch:
    image: apache/couchdb
    restart: always
    ports:
      - 31111:5984 
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - ${CD}/couchdata:/opt/couchdb/data
      - ${CD}/couchinit:/opt/couchdb/etc/local.d